<?php if ($this->isLoggedIn()) { ?>
    <div id="julienreviews-main-form">
        <div class="page-title"><h1>Write Your Review</h1></div>
        <p>Review for <?php echo $this->getProductName() ?></p>

        <div class="julienreviews-left">
            <div class="review-image"><img src="<?php echo $this->getProductImageUrl(); ?>"></div>
            <div class="review-tips">
                <?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('review_tips')->toHtml(); ?>
            </div>
            <?php // echo Mage::getUrl('julienreviews/guidelines'); ?>
        </div>
        <form id="julienReviewForm" action="<?php echo Mage::getUrl('julienreviews/write/preview'); ?>" method="POST">
            <input style="display: none;" autofocus>
            <input type="hidden" name="review-product-id" value="<?php echo $this->getProductId() ?>">
            <input type="hidden" name="review-customer-id" value="<?php echo $this->getCustomerId() ?>">

            <label for="review-stars">How do you rate this product?</label>
            <select id="review-stars" name="review-stars" class="required-entry">
                <option value=""><?php echo $this->__('Please Select') ?></option>
                <option value="5" <?php if ($this->postData['review-stars'] == 5) echo 'selected="selected"'; ?>>5 stars</option>
                <option value="4" <?php if ($this->postData['review-stars'] == 4) echo 'selected="selected"'; ?>>4 stars</option>
                <option value="3" <?php if ($this->postData['review-stars'] == 3) echo 'selected="selected"'; ?>>3 stars</option>
                <option value="2" <?php if ($this->postData['review-stars'] == 2) echo 'selected="selected"'; ?>>2 stars</option>
                <option value="1" <?php if ($this->postData['review-stars'] == 1) echo 'selected="selected"'; ?>>1 stars</option>
            </select>

            <label for="review-recommended">Would you recommend this item to a friend?</label>
            <select id="review-recommended" name="review-recommended" class="required-entry">
                <option value=""><?php echo $this->__('Please Select') ?></option>
                <option value="Yes" <?php if ($this->postData['review-recommended'] == 'Yes') echo 'selected="selected"'; ?>>Yes</option>
                <option value="No" <?php if ($this->postData['review-recommended'] == 'No') echo 'selected="selected"'; ?>>No</option>
            </select>

            <label for="review-headline">Review Headline</label>
            <input type="text" id="review-headline" name="review-headline"
                   value="<?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8'); ?>">

            <label for="review-comments">Write your review here</label>
            <textarea id="review-comments" name="review-comments"><?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8'); ?></textarea>

            <br/><br/><br/>

            <h1>Tell Us About Yourself</h1>

            <label for="review-purchase-location">Where did you buy this item?</label>
            <select id="review-purchase-location" name="review-purchase-location">
                <option value=""><?php echo $this->__('Please Select') ?></option>
                <option value="JulienFarel.com" <?php if ($this->postData['review-purchase-location'] == "JulienFarel.com") echo 'selected="selected"'; ?>>
                    JulienFarel.com
                </option>
                <option value="Bergdorf Goodman" <?php if ($this->postData['review-purchase-location'] == "Bergdorf Goodman") echo 'selected="selected"'; ?>>
                    Bergdorf Goodman
                </option>
                <option value="Other" <?php if ($this->postData['review-purchase-location'] == "Other") echo 'selected="selected"'; ?>>Other</option>
            </select>

            <label for="review-age-range">Age Range</label>
            <select id="review-age-range" name="review-age-range">
                <option value=""><?php echo $this->__('Please Select') ?></option>
                <option value="18 - 24" <?php if ($this->postData['review-age-range'] == "18 - 24") echo 'selected="selected"'; ?>>18 - 24</option>
                <option value="25 - 34" <?php if ($this->postData['review-age-range'] == "25 - 34") echo 'selected="selected"'; ?>>25 - 34</option>
                <option value="35 - 44" <?php if ($this->postData['review-age-range'] == "35 - 44") echo 'selected="selected"'; ?>>35 - 44</option>
                <option value="45 - 54" <?php if ($this->postData['review-age-range'] == "45 - 54") echo 'selected="selected"'; ?>>45 - 54</option>
                <option value="over 54" <?php if ($this->postData['review-age-range'] == "over 54") echo 'selected="selected"'; ?>>over 54</option>
            </select>

            <label for="review-city-state">Enter your city and state</label>
            <input type="text" id="review-city-state" name="review-city-state" value="<?php echo $this->postData['review-city-state']; ?>">

            <?php if (Mage::helper('alliance_julienreviews')->getConfigEnableCustomerNotification()) { ?>
                <label for="review-notify">Would you like to be notified by email when your review is posted?</label>
                <select id="review-notify" name="review-notify">
                    <option value=""><?php echo $this->__('Please Select') ?></option>
                    <option value="Yes" <?php if ($this->postData['review-notify'] == "Yes") echo 'selected="selected"'; ?>>Yes</option>
                    <option value="No" <?php if ($this->postData['review-notify'] == "No") echo 'selected="selected"'; ?>>No</option>
                </select>
            <?php } ?>

            <br/><br/>
            <button type="submit" value="Preview" title="Preview" class="button btn-preview"><span><span>Preview</span></span></button>

        </form>
        <script type="text/javascript">
            //<![CDATA[
            var julienReviewForm = new VarienForm('julienReviewForm', true);
            //]]>
        </script>
    </div>
<?php } else { ?>
    <div id="julienreviews-must-login">
        <div class="page-title"><h1>Must Be Logged In</h1></div>
        <?php echo Mage::helper('alliance_julienreviews')->__('Only registered users can write reviews. Please, '); ?>
        <a href="<?php echo Mage::helper('customer')->getLoginUrl(); ?>"><?php echo Mage::helper('alliance_julienreviews')->__('log in'); ?></a>
        <?php echo Mage::helper('alliance_julienreviews')->__('or '); ?>
        <a href="<?php echo Mage::helper('customer')->getRegisterUrl(); ?>"><?php echo Mage::helper('alliance_julienreviews')->__('register'); ?></a>.
    </div>
<?php } ?>