<!-- some temporary styles -->
<style>
    #julienreviews-guidelines {
        color: #f05340;
        font-family: "PlutoSansCondMedium", "Helvetica Neue", "Helvetica", Arial, sans-serif;
        font-size: 14px;
        letter-spacing: 1px;
        border: 2px solid #00bfff;
        margin: 5px;
        clear: both;
        padding: 10px;
    }
</style>
<!-- end temporary styles -->
<div id="julienreviews-guidelines">
    <div style="color: #00bfff; font-weight: bold;">Review Guidelines Block</div>
    JulienReviews Guidelines Page
</div>