<?php
	$avg = $this->postData['review-stars'];
	$avgWidth = $avg/5;
	$percent = round((float)$avgWidth * 100 ) . '%';
?>

<div id="julienreviews-preview-form">
    <div class="page-title"><h1>Review Preview</h1></div>
    <div class="julienreviews-right">
	    <h2><?php echo htmlspecialchars($this->postData['review-headline'], ENT_QUOTES) ?></h2>
		<div class="rating-box">
	    	<div class="rating" style="width:<?php echo $percent; ?>"></div>
	    </div>
		<br />
	    <?php echo nl2br(htmlspecialchars($this->postData['review-comments'], ENT_QUOTES)) ?>
	    <form action="<?php echo Mage::getUrl('julienreviews/write/index/id/'.$this->postData['review-product-id']); ?>" method="POST">
	        <input type="hidden" name="review-product-id" value="<?php echo $this->product_id ?>">
	        <input type="hidden" name="review-customer-id" value="<?php echo $this->customer_id ?>">
			<br />
			Recommended? <?php echo $this->postData['review-recommended'] ?>
			<br />
			Purchased At? <?php echo $this->postData['review-purchase-location'] ?>
			<br />
			Age Range? <?php echo $this->postData['review-age-range'] ?>
			<br />
			Location? <?php echo $this->postData['review-city-state'] ?>
			<br />
			<?php if (Mage::helper('alliance_julienreviews')->getConfigEnableCustomerNotification()) { ?>
			Notify? <?php echo $this->postData['review-notify'] ?>
			<br />
			<?php } ?>			
			
	        <input type="hidden" name="review-stars" value="<?php echo $this->postData['review-stars'] ?>">
	        <input type="hidden" name="review-recommended" value="<?php echo $this->postData['review-recommended'] ?>">
	        <input type="hidden" name="review-headline" value="<?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8') ?>">
	        <input type="hidden" name="review-comments" value="<?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8') ?>">
	        <input type="hidden" name="review-purchase-location" value="<?php echo $this->postData['review-purchase-location'] ?>">
	        <input type="hidden" name="review-age-range" value="<?php echo $this->postData['review-age-range'] ?>">
	        <input type="hidden" name="review-city-state" value="<?php echo $this->postData['review-city-state'] ?>">
	        <input type="hidden" name="review-notify" value="<?php echo $this->postData['review-notify'] ?>">
	        
	        <button type="submit" value="Edit" title="Edit" class="button"><span><span>Edit</span></span></button>
	    </form>
	
	    <form action="<?php echo Mage::getUrl('julienreviews/submit/save'); ?>" method="POST">
	        <input type="hidden" name="review-product-id" value="<?php echo $this->product_id ?>">
	        <input type="hidden" name="review-customer-id" value="<?php echo $this->customer_id ?>">
	        <input type="hidden" name="review-stars" value="<?php echo $this->postData['review-stars'] ?>">
	        <input type="hidden" name="review-recommended" value="<?php echo $this->postData['review-recommended'] ?>">
	        <input type="hidden" name="review-headline" value="<?php echo htmlentities($this->postData['review-headline'], ENT_QUOTES, 'UTF-8') ?>">
	        <input type="hidden" name="review-comments" value="<?php echo htmlentities($this->postData['review-comments'], ENT_QUOTES, 'UTF-8') ?>">
	        <input type="hidden" name="review-purchase-location" value="<?php echo $this->postData['review-purchase-location'] ?>">
	        <input type="hidden" name="review-age-range" value="<?php echo $this->postData['review-age-range'] ?>">
	        <input type="hidden" name="review-city-state" value="<?php echo $this->postData['review-city-state'] ?>">
	        <input type="hidden" name="review-notify" value="<?php echo $this->postData['review-notify'] ?>">
	        <button type="submit" value="Save" title="Save" class="button btn-save"><span><span>Save</span></span></button>
	    </form>
		
    </div>
</div>