<div class="categoryfilter-container">
	
	<div class="block-left">	
		<img src="<?php echo $this->getSkinUrl('images/SCIENCEOFHAIR.png');?>" width=234 alt="logo"/>
		
		<div class="destination-staff-header">
			Filter By
			<a href="#" id="reset-all-filter">Reset All</a>
		</div>
		<?php echo $this->getChildHtml('attributes.nav');?>
	</div>
	<div class="block-right">
		<div class="mobile">
			<img src="<?php echo $this->getSkinUrl('images/SCIENCEOFHAIR.png');?>" width=234 alt="logo"/>
		</div>
		<div class="rotation-banner-uique">
			<div class="cart-message" id="loading" >
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('rotating-hdr-msg')->toHtml(); ?>
			</div>
		</div>
	
		<div class="categoryfilter-dropboxs">
			<?php echo $this->getChildHtml('categories.nav');?>
		</div>
		
		<div class="top-banner">
			<?php if(Mage::getModel('catalog/category')->load($this->getCategory()->getId())->getImageUrl()==null){ ?>
				<!-- default banner -->
				<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/julienfarel/jf/images/category_top_banner.png"; ?>" label="category_top_banner"/>
			<?php }else { ?>
				<!-- real banner -->
				<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('catalog_top_banner_block')->toHtml(); ?>
			<?php } ?>
		</div>
		<div class="categoryfilter-wrap">
		<div class="categoryfilter-products" id="products-list">
			<?php
			$products = $this->getProducts();
			$productcount = 0 ;
			foreach($products as $_product) {
				if($productcount != 9){
					// Get Attributes.
					$attributes = $this->getAttributes();
					$dataGroups = "";
					foreach($attributes as $oneAttribute) {
						$staffAttribute = $_product->getData($oneAttribute['code']);
						if($staffAttribute) {
							$staffAttributeArray = explode(',', $staffAttribute);
							foreach($staffAttributeArray as $oneStaffAttribute) {
								$dataGroups .= '"'.$oneAttribute['clean-code'].'-'.$oneStaffAttribute.'", ';
							}
						}
					}
				?>
				<div class="product item" <?php if(! empty($dataGroups)) echo " data-groups='[".substr($dataGroups, 0, -2)."]'";?>>
					<div class="quick-view">
						
						<div class="quick-view-container">
							<div class="quick-step-margin">
								<?php /* mmc removed
								<div class="name product-name"><a href="<?php echo $_product->getProductUrl();?>"><?php echo $this->stripTags($_product->getName(), null, true);?></a></div> */?>
								<button type="button" class="button" onclick="location.href='<?php echo $_product->getProductUrl() ?>'"><span><span><?php echo $this->__('View Details'); ?></span></span></button>
								<button type="button" class="button fancybox" data-fancybox-type="iframe"
										href="<?php echo Mage::getUrl('quickview/product/view/id/' . $_product->getId()); ?>">
									<span><span><?php echo $this->__('Quick View'); ?></span></span></button>
							</div>
						</div>
						<a href="<?php echo $_product->getProductUrl();?>"><img class="product-img"
							 src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->keepFrame(false)->resize(800); ?>"
							 alt=""/></a>

					</div>
					<div class="product-data">
						<?php $productname = strlen($this->stripTags($_product->getName(), null, true)) > 80 ? substr($this->stripTags($_product->getName(), null, true),0,80)."...":$this->stripTags($_product->getName(), null, true); ?>
						<div class="product-title product-name" style="text-overflow:ellipsis;"><a href="<?php echo $_product->getProductUrl();?>"><?php echo $productname; ?></a></div>
                        <?php
                        $avg = Mage::helper('alliance_julienreviews')->getStarAverage($_product->getId());
                        $avgWidth = $avg/5;
                        $percent = round((float)$avgWidth * 100 ) . '%';
                        ?>
                        <div id="julienreviews-product-summary">
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo $percent; ?>"></div>
                            </div>
                        </div>
						<div class="descriptions"><?php echo $this->stripTags($_product->getDescription());?></div>
						<div class="category-price">
							<div class="product-price">
							<?php
							if($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'subscription_configurable'): ?>
										   <?php
								$var_price = '';	
								$k = 0;
								$associatedProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null,$_product);  
								foreach($associatedProducts as $pro) {
									$status = $pro->getStatus();
									$stock = $pro->getIsInStock();
									if ( ($status == 1) && ($stock==1) ) {
										$var_price[] = $pro->getPrice();
										$k++;
									}	
								}  
								sort($var_price);
								$lower_price = reset($var_price);
								$higher_price = end($var_price);
								?>
								<?php if($k > 1 ): ?>
									<div class="price-box">
										<span class="regular-price">
											<span class="price">
												<?php if($lower_price !== $higher_price) :?>
													<?php echo Mage::helper('core')->currency($lower_price) . " - " . Mage::helper('core')->currency($higher_price); ?>
												<?php else : ?>
												<?php echo Mage::helper('core')->currency($lower_price);?>
												<?php endif ?>
											</span>                
										</span>
									</div>
								<?php endif; ?>	
								
								<?php if($k == 0 || $k==1 ): ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
								<?php endif; ?>
								
							<?php else: ?>					
								<?php echo $this->getPriceHtml($_product, true) ?>
							<?php endif; ?>	                                                   
							</div>
						</div>
						<?php if($_product->isSaleable()): ?>
								<div style="float:right; margin-bottom:20px;" id="cart_button_<?php echo $_product->getId(); ?>"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button button-gray btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
						<?php else: ?>
							<div  style="float:right; margin-bottom:20px;"><div class="button unhover out-stock" style="background:#9E007E !important;"><span><span>sold out</span></span></div></div>								
						<?php endif; ?>						
					</div>
				</div>
			<?php
					$productcount++;
				}else{
			?>
				<div class="product insert">
				
					<?php if(Mage::getModel('catalog/category')->load($this->getCategory()->getId())->getThumbnail()==null){ ?>
						<!-- default banner -->
						<img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/julienfarel/jf/images/category_insert-new.png"; ?>" label="category-insert" />
					<?php }else { ?>
						<!-- real banner -->
						<img src="<?php echo Mage::getBaseUrl('media').'catalog/category/'.Mage::getModel('catalog/category')->load($this->getCategory()->getId())->getThumbnail(); ?>" label="category_small_image"/>
					<?php } ?>				
					
				</div>
				
				<div class="product item" <?php if(! empty($dataGroups)) echo " data-groups='[".substr($dataGroups, 0, -2)."]'";?>>
					<div class="quick-view">
						<img class="product-img" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->keepAspectRatio(true)->keepFrame(false)->resize(800,null);?>" alt=""/>
						<div class="quick-view-container">
							<div class="quick-step-margin">
								<div class="name product-name" style="display:none;"><a href="<?php echo $_product->getProductUrl();?>"><?php echo $this->stripTags($_product->getName(), null, true);?></a></div>
								<button type="button" class="button" onclick="location.href='<?php echo $_product->getProductUrl() ?>'"><span><span><?php echo $this->__('View Details'); ?></span></span></button>
								<button type="button" class="button fancybox" data-fancybox-type="iframe"
										href="<?php echo Mage::getUrl('quickview/product/view/id/' . $_product->getId()); ?>">
									<span><span><?php echo $this->__('Quick View'); ?></span></span></button>
							</div>
						</div>
					</div>
					<div class="product-data">
						<?php $productname = strlen($this->stripTags($_product->getName(), null, true)) > 80 ? substr($this->stripTags($_product->getName(), null, true),0,80)."...":$this->stripTags($_product->getName(), null, true); ?>
						<div class="product-title" style="text-overflow:ellipsis;"><?php echo $productname; ?></div>
                        <?php
                        $avg = Mage::helper('alliance_julienreviews')->getStarAverage($_product->getId());
                        $avgWidth = $avg/5;
                        $percent = round((float)$avgWidth * 100 ) . '%';
                        ?>
                        <div id="julienreviews-product-summary">
                            <div class="rating-box">
                                <div class="rating" style="width:<?php echo $percent; ?>"></div>
                            </div>
                        </div>
						<div class="descriptions"><?php echo $_product->getDescription();?></div>
						<div class="category-price">
							<div class="product-price">
							<?php
							if($_product->getTypeId() == 'configurable' || $_product->getTypeId() == 'subscription_configurable'): ?>
										   <?php
								$var_price = '';	
								$k = 0;
								$associatedProducts = Mage::getModel('catalog/product_type_configurable')->getUsedProducts(null,$_product);  
								foreach($associatedProducts as $pro) {
									$status = $pro->getStatus();
									$stock = $pro->getIsInStock();
									if ( ($status == 1) && ($stock==1) ) {
										$var_price[] = $pro->getPrice();
										$k++;
									}	
								}  
								sort($var_price);
								$lower_price = reset($var_price);
								$higher_price = end($var_price);
								?>
								<?php if($k > 1 ): ?>
									<div class="price-box">
										<span class="regular-price">
											<span class="price">
												<?php if($lower_price !== $higher_price) :?>
													<?php echo Mage::helper('core')->currency($lower_price) . " - " . Mage::helper('core')->currency($higher_price); ?>
												<?php else : ?>
												<?php echo Mage::helper('core')->currency($lower_price);?>
												<?php endif ?>
											</span>                
										</span>
									</div>
								<?php endif; ?>	
								
								<?php if($k == 0 || $k==1 ): ?>
									<?php echo $this->getPriceHtml($_product, true) ?>
								<?php endif; ?>
								
							<?php else: ?>					
								<?php echo $this->getPriceHtml($_product, true) ?>
							<?php endif; ?>	                                                   
							</div>						
						</div>
						<?php if($_product->isSaleable()): ?>
							<div  style="float:right; margin-bottom:20px;" id="cart_button_<?php echo $_product->getId(); ?>"><button type="button" title="<?php echo $this->__('Add to Cart') ?>" class="button button-gray btn-cart" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>');"><span><span><?php echo $this->__('Add to Cart') ?></span></span></button></div>
						<?php else: ?>
							<div  style="float:right; margin-bottom:20px;"><div class="button unhover out-stock" style="background:#9E007E !important;"><span><span>sold out</span></span></div></div>								
						<?php endif; ?>
					</div>
				</div>			
			<?php	
				$productcount = 11;
				}
			}
			?>
		<div class="loading-hover"></div>	
		</div>
		</div><!-- mmc 2ten close categoryfilter-wrap -->
		<div class="products-list-empty">
			<h3><span>Not found</span></h3>
			<p>Sorry, there were no product matching those attributes</p>
		</div>

	</div>
</div>

<script type="text/javascript">
	jQuery(document).ready(function () {
		jQuery(".fancybox").fancybox({
			padding: 10,
			helpers: {
				overlay: {
					locked: false
				}
			},
			maxWidth: 1024,
			maxHeight: 450,
			fitToView: false,
			width: '100%',
			height: '100%',
			autoSize: false,
			closeClick: false,
			openEffect: 'none',
			closeEffect: 'none',
			afterClose: function() {
				var miniCart = $$('.top-cart')[0];
				miniCart.hide();
				
				new Ajax.Request('/scrapper', {
					method: 'get',
					onComplete: function(response) {
						var cart = response.responseText.substr(response.responseText.indexOf('<div class="top-cart"'));
						cart = cart.substr(0, cart.indexOf('<'+'script type="text/javascript">'));
						cart = cart + '</div></div></div>';
						
						miniCart.outerHTML = cart;
						miniCart.show();
						
						AjaxCart.init();
					}
				});
			}
		});
	});
</script>
