<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?php echo $this->getLang() ?>" lang="<?php echo $this->getLang() ?>">
<head>
	<base target="_parent">
	<?php echo $this->getChildHtml('head') ?>
</head>
<body<?php echo $this->getBodyClass() ? ' class="' . $this->getBodyClass() . '"' : '' ?>>
	<?php echo $this->getChildHtml('after_body_start') ?>
	<div class="wrapper">
		<div class="page">
			<?php echo $this->getChildChildHtml('header', 'topCart') ?>
			<div class="main-container col1-layout">
				<div class="main">
					<div class="col-main content-generic">
						<?php echo $this->getChildHtml('content') ?>
					</div>
				</div>
			</div>
			<?php echo $this->getChildHtml('before_body_end') ?>
		</div>
	</div>

	<?php echo $this->getAbsoluteFooter() ?>
</body>
</html>