<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $collection = $this->getCollection(); ?>
<?php if ($collection->getSize()) { ?>
    <div id="julienreviews-main-display">
        <h2>Customer Reviews for <span><?php echo $this->product_name; ?></span></h2>
		<br />
		<div class="button-sets">
        <?php if ($this->review_count > 0) { ?>
            <a class="button" href="<?php echo Mage::getUrl('julienreviews/write/index/id/'.$this->product_id); ?>">Write your Review</a>
        <?php } else { ?>
            <a class="button button-gray" href="<?php echo Mage::getUrl('julienreviews/write/index/id/'.$this->product_id); ?>">Be the first to review this product!</a>
        <?php } ?>
			<a class="button button-gray" href="<?php echo $this->getBackUrl(); ?>">Back to Main Product Info</a>
		</div>
		<br />
        <?php $reviewcounter = 1; ?>
        <?php $customers = array(); ?>
        <?php $_odd = ''; ?>
        <?php foreach ($collection as $review) { ?>
            <?php if (!in_array($review->getCustomerId(), $customers)) { ?>
                <?php $customers[] = $review->getCustomerId(); ?>
                <?php $helpful = $this->getHelpfuls($review->getId()); ?>
                <div style="margin: 10px 5px; clear: both; padding: 10px; border-top:3px solid #ddd;">
                    <?php if ($helpful['helpful_total'] > 0) { ?>
                        <?php if ($helpful['helpful_total'] == 1) { ?>
                            <?php echo $helpful['helpful_yes'] == 1 ? 'One customer finds this review helpful' : 'One customer did not find this review helpful'; ?>
                        <?php } else {?>
                            <?php echo $helpful['helpful_yes'] ?> out of <?php echo $helpful['helpful_total'] ?> customers find this review helpful
                        <?php } ?>
                        <br>
                    <?php } ?>
					
					<?php
						$avg = $review->getStarRating(); 
						$avgWidth = $avg/5;
						$percent = round((float)$avgWidth * 100 ) . '%';
					?>
					<br>
					<div class="rating-box">
						<div class="rating" style="width:<?php echo $percent; ?>"></div>
					</div>
                    <br>
                    <span style="font-size: 18px; font-weight: bold;"><?php echo htmlentities($review->getReviewHeadline(), ENT_QUOTES, 'UTF-8') ?></></span>
                    <?php if ($review->getReviewText()) { ?>
                        <br>
                        <br>
                        <?php echo nl2br(htmlentities($review->getReviewText(), ENT_QUOTES, 'UTF-8')) ?>
                        <br>
                        <br>
                    <?php } ?>
                    <?php echo $this->getTopContributorText($review->getCustomerId()) ?>
                    <br>
                    <br>
                    Date: <?php echo $review->getDate() ?>
                    <br>
                    <?php if ($review->fetchCustomerName()) { ?>
                        First Name: <?php echo $review->fetchCustomerName() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getLocation()) { ?>
                        City &amp; State: <?php echo $review->getLocation() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getPurchasedAt()) { ?>
                        Location of Purchase: <?php echo $review->getPurchasedAt() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getSkinConcern()) { ?>
                        Skin Concern: <?php echo $review->getSkinConcern() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getAgeRange()) { ?>
                        Age Range: <?php echo $review->getAgeRange() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getOwnedFor()) { ?>
                        Owned For: <?php echo $review->getOwnedFor() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getOftenUsed()) { ?>
                        How Often Used: <?php echo $review->getOftenUsed() ?>
                        <br>
                    <?php } ?>
                    <?php if ($review->getMemberStatus()) { ?>
                        Member Status: <?php echo $review->getMemberStatus() ?>
                        <br>
                    <?php } ?>
                    <?php if ($this->customerLoggedIn()) { ?>
                        <br>
                        <?php if ($helpful['customer_helpful'] == 'Null') { ?>
							<?php /*
                            <div id="found-review-helpful-input-<?php echo $reviewcounter; ?>">
                                Did you find this review helpful? <div id="Helpful-Yes-AJAX-<?php echo $reviewcounter; ?>" style="cursor: pointer; display: inline-block; text-decoration: underline;">Yes</div> / <div id="Helpful-No-AJAX-<?php echo $reviewcounter; ?>" style="cursor: pointer; display: inline-block; text-decoration: underline;">No</div>
                            </div>
                            <div id="found-review-helpful-<?php echo $reviewcounter; ?>" class="found-review-helpful" style="display: none;">
                                You found this review helpful!
                            </div>
                            <div id="found-review-unhelpful-<?php echo $reviewcounter; ?>" class="found-review-unhelpful" style="display: none;">
                                You did not find this review helpful.
                            </div>
							*/ ?>
							<div id="found-review-helpful-input-<?php echo $reviewcounter; ?>">
								Did you find this review helpful? <div id="Helpful-Yes-AJAX-<?php echo $reviewcounter; ?>" style="margin-left:20px; display: inline-block; cursor: pointer;"><img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/julienfarel/jf/images/yes.png";?>' label="yes"></div><div id="Helpful-No-AJAX-<?php echo $reviewcounter; ?>" style="margin-left:7px; display: inline-block; cursor: pointer;"><img src="<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/julienfarel/jf/images/no.png";?>" label="no"></div>
							</div>
							<div id="found-review-helpful-<?php echo $reviewcounter; ?>" class="found-review-helpful" style="display: none;">
								You found this review helpful!
							</div>
							<div id="found-review-unhelpful-<?php echo $reviewcounter; ?>" class="found-review-unhelpful" style="display: none;">
								You did not find this review helpful.
							</div>
								
                        <?php } else { ?>
                            <?php if ($helpful['customer_helpful'] == 'Yes') { ?>
                                <div class="found-review-helpful">
                                    You found this review helpful!
                                </div>
                            <?php } elseif ($helpful['customer_helpful'] == 'No') { ?>
                                <div class="found-review-unhelpful">
                                    You did not find this review helpful.
                                </div>
                            <?php } ?>
                        <?php } ?>
                    <?php } ?>
                </div>
                <?php $reviewcounter++; ?>
            <?php } ?>
        <?php } ?>
        <?php echo $this->getPagerHtml(); ?>
    </div>
    <script>
        <?php $reviewcounter = 1; ?>
        <?php foreach ($this->_collection as $review) { ?>
        jQuery('#Helpful-Yes-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/julienreviews/submit/helpyes/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-helpful-<?php echo $reviewcounter; ?>').show();
        });

        jQuery('#Helpful-No-AJAX-<?php echo $reviewcounter; ?>').click(function() {
            jQuery.ajax({
                url: '/julienreviews/submit/helpno/customerid/<?php echo $this->customer_id; ?>/reviewid/<?php echo $review->getId(); ?>'
            });
            jQuery('#found-review-helpful-input-<?php echo $reviewcounter; ?>').hide();
            jQuery('#found-review-unhelpful-<?php echo $reviewcounter; ?>').show();
        });
        <?php $reviewcounter++; ?>
        <?php } ?>
    </script>
<?php } else { ?>
    No reviews found.
<?php } ?>