<?php
/**
 * Moo Extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   Moo
 * @package    Moo_Catalog
 * @author     Mohamed Alsharaf <mohamed.alsharaf@gmail.com>
 * @copyright  Copyright (c) 2010 Mohamed Alsharaf. (http://jamandcheese-on-phptoast.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
/**
 * Product media data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php
$_product = $this->getProduct();
$_helper = $this->helper('catalog/output');
?>
<?php
$galleryImages = $this->getGalleryImages();
if (count($galleryImages) > 0) {
    $gallery = '';
    foreach ($galleryImages as $_image) {
        $gallery .= '<li>'
                . '<a id="cloud-zoom-gallery' . $i . '" href="' . $this->helper('catalog/image')->init($this->getProduct(), 'image', $_image->getFile()) . '" '
                . 'rel="useZoom: \'cloudZoom\', smallImage: \'' . $this->getCloudImage($this->getProduct(), $_image) . '\'" class="cloud-zoom-gallery" title="' . $this->htmlEscape($_image->getLabel()) . '">'
                . '<img src="' . $this->helper('catalog/image')->init($this->getProduct(), 'thumbnail', $_image->getFile())->resize(160) . '" width="56" height="56" alt="' . $this->htmlEscape($_image->getLabel()) . '" />'
                . '</a></li>';
    }
}
?>

<?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
    <p class="product-image product-image-zoom">
        <a rel="<?php echo $this->renderCloudOptions(); ?>" <?php echo $this->renderLightboxOptions(); ?> href="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" class="cloud-zoom" id="cloudZoom">
            <?php
            $_img = '<img id="image" src="' . $this->getCloudImage($_product) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
            echo $_helper->productAttribute($_product, $_img, 'image');
            ?>
        </a>
    </p>
    <?php if (isset($gallery)): ?>
		<div class="more-views">
			<ul>
			<?php echo $gallery; ?>
			<?php $gallery_vedio = $_product->getResource()->getAttribute('gallery_video');
			$exist = $gallery_vedio ? $gallery_vedio->getFrontend()->getValue($_product) : false; ?>
			<?php if(!empty($exist)) { ?>
			<li class="gallery_vedio" style='background:url("<?php echo '//img.youtube.com/vi/'.$_product->getResource()->getAttribute('gallery_video')->getFrontend()->getValue($_product).'/0.jpg'; ?>") no-repeat;'>
				<a class="youtube" rel="<?php echo $gallery_vedio->getFrontend()->getValue($_product); ?>" href="#">
					<div class="player-layer"><img src='<?php echo Mage::getBaseUrl(Mage_Core_Model_Store::URL_TYPE_SKIN)."frontend/julienfarel/jf/images/player.png"; ?>' label="olayer-layer" /></div>
				</a>
			</li>
			<?php } ?>			
			</ul>
		</div>
    <?php endif; ?>
<?php else: ?>
    <p class="product-image">
        <?php
        $_img = '<img src="' . $this->helper('catalog/image')->init($_product, 'image')->resize(265) . '" alt="' . $this->htmlEscape($this->getImageLabel()) . '" title="' . $this->htmlEscape($this->getImageLabel()) . '" />';
        echo $_helper->productAttribute($_product, $_img, 'image');
        ?>
    </p>
<?php endif; ?>

<div class="social-icons">
	<label>share:</label>
    <span class='st_facebook' displayText='Facebook' st_url='<?php echo $_product->getProductUrl() ?>'
        st_title='<?php echo $_helper->productAttribute($_product, $_product->getTitle(), 'title'); ?> <?php echo $_helper->productAttribute($_product, $_product->getSubTitle(), 'sub_title') ?>'
        st_image='<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>'></span>
    <span class='st_twitter' displayText='Tweet' st_url='<?php echo $_product->getProductUrl() ?>'
        st_title='<?php echo $_helper->productAttribute($_product, $_product->getTitle(), 'title'); ?> <?php echo $_helper->productAttribute($_product, $_product->getSubTitle(), 'sub_title') ?>'
        st_image='<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>'></span>
    <span class='st_pinterest' displayText='Pinterest' st_url='<?php echo $_product->getProductUrl() ?>'
        st_title='<?php echo $_helper->productAttribute($_product, $_product->getTitle(), 'title'); ?> <?php echo $_helper->productAttribute($_product, $_product->getSubTitle(), 'sub_title') ?>'
        st_image='<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>'></span>
    <span class='st_googleplus' displayText='Google +' st_url='<?php echo $_product->getProductUrl() ?>'
        st_title='<?php echo $_helper->productAttribute($_product, $_product->getTitle(), 'title'); ?> <?php echo $_helper->productAttribute($_product, $_product->getSubTitle(), 'sub_title') ?>'
        st_image='<?php echo $this->helper('catalog/image')->init($_product, 'image') ?>'></span>
</div>
