<div class="nav-cover">&nbsp;</div>

<div class="contactform clearfix">

<div class="breadcrumbs">
    <ul>
        <li class="home"><a href="<?php echo Mage::getBaseUrl(); ?>" title="Go to Home Page">Home</a> <span>/ </span></li>
        <li class="cms_page"><strong>Contact Us</strong></li>
	</ul>
    <div class="breadcrumb-tab">&nbsp;</div>
</div>

	<form id="contactusForm" name="contactusForm" class="contactusForm" action="<?php echo $this->getUrl( 'contact/index/submit' );?>" method="post" >
	
		<h2>contact us</h2>
	
		<div class="contactfname">
			<label for="firstname" class="required"><em>*</em><?php echo $this->__('First Name') ?></label>
			<div class="input-box">
				<input name="ctfirstname" id="tfirstname" title="<?php echo $this->__('firstname') ?>" class="required-entry" type="text"/>
			</div>
		</div>
	
		<div class="contactlname">
			<label for="lastname" class="required"><em>*</em><?php echo $this->__('Last Name') ?></label>
			<div class="input-box">
				<input name="ctlastname" id="tlastname" title="<?php echo $this->__('lastname') ?>" class="required-entry" type="text"/>
			</div>
		</div>
	
		<div class="emailaddress">
			<label for="email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
			<div class="input-box">
				<input name="ctemail" id="temail" title="<?php echo $this->__('phone') ?>" class="required-entry validate-email" type="text"/>
			</div>
		</div>
	
		<div class="phonenumber">
			<label for="phone"><?php echo $this->__('Phone') ?></label>
			<div class="input-box">
				<input name="ctphone" id="phone" title="<?php echo $this->__('phone') ?>" class="" type="text"/>
			</div>
		</div>
	
		<div class="contactmessages">
			<label class="full-width" for="tmessages" class="required"><em>*</em><?php echo $this->__('Type your message here') ?></label>
			<div class="input-box">
				<textarea cols="40" rows="5" name="ctmessages" id="tmessages" class="required-entry"></textarea>
			</div>
		</div>
	
		<div class="contact-privacy">
			<p>By submitting your email you agree to the Julien Farel privacy policy<br />
			<em>*</em>Fields are mandatory</p>
		</div>
		<button type="submit" id="contactsubmit">submit</button>
	</form>
	
	<div id="contactRight">
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-form-sidebar-top')->toHtml(); ?>
		<?php echo $this->getLayout()->createBlock('cms/block')->setBlockId('contact-form-sidebar-bottom')->toHtml(); ?>	
	</div>
</div>

<script type="text/javascript">
//<![CDATA[
    var contactForm = new VarienForm('contactusForm',true);
//]]>
</script>

























