<div class="contactform clearfix">
	<div class="breadcrumbs">
		<ul>
			<li class="home"><a href="<?php echo Mage::getBaseUrl(); ?>" title="Go to Home Page">Home</a> <span>/ </span></li>
			<li class="cms_page"><strong>Contact Us</strong></li>
		</ul>
		<div class="breadcrumb-tab">&nbsp;</div>
	</div>

	<div id="formSuccess" >
		<h1>THANK YOU</h1>
		<p>Thank you for contacting us. We will respond to your inquiry shortly.</p>
	</div>
</div>	