<?php
if((int)Mage::helper('checkout/cart')->getItemsCount() > 0) {
?>
<div class="cart-right">
	<dl id="collateral-tabs" class="collateral-tabs">
		<dt class="tab"><span><?php echo $this->__('Free Samples') ?></span></dt>
		<dd class="tab-container">
		   <div class="tab-content" style="display: block;">
			<div class="tab-desc">
	<?php echo $this->getChildHtml('freesamples');?>
			</div>
		   </div>
		</dd>
		<dt class="tab"><span class="wishlist-holder"><div class="wishlist-icon"><?php echo $this->__('Wishlist') ?></div></span></dt>
		<dd class="tab-container">
		   <div class="tab-content" style="display: block;">
			<div class="tab-desc">
	<?php echo $this->getChildHtml('ajaxcart.wishlist');?>
			</div>
		   </div>
		</dd>
	</dl>
	
	<script type="text/javascript">
	//<![CDATA[
	// var collateralTabs = new Enterprise.Tabs('collateral-tabs');
	// Event.observe(window, 'load', function() {
		// collateralTabs.select();
	// });
	//]]>
	</script>
</div>
<?php
}
?>